kind: pipeline
type: docker
name: netztp

steps:
- name: tag
  image: alpine/git
  commands:
    - echo -n $(git log -n 1 --format=%h) > .tags

- name: docker
  image: plugins/docker
  settings:
    repo: registry.yzguy.io/netztp
