#!/bin/sh
set -e

cd "$(dirname "$0")/.."

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="venv"
fi

ACTIVATE="$VENV_NAME/bin/activate"
if [ ! -f "$ACTIVATE" ]; then
    echo "$ACTIVATE does not exist, run ./script/bootstrap" >&2
    exit 1
fi
. "$ACTIVATE"

coverage run --branch --source=netztp "$(command -v nosetests)" --with-xunit "$@"
coverage html
coverage xml
coverage report --show-missing
coverage report | grep ^TOTAL | grep -qv 100% && {
    echo "Incomplete code coverage" >&2
    exit 1
} || echo "Code coverage 100%"
