from flask import make_response, jsonify, request, url_for, redirect
from app.eos import bp

from datetime import datetime
import hashlib

startup_config = '''
hostname veos.lab
ip domain-name yzguy.io
!
username admin privilege 15 role network-admin secret admin
end
'''

# First Step: DHCP tells EOS to request bootstrap
@bp.route('/ztp/bootstrap')
def ztp_bootstrap():
    # TODO: Need to replace $SERVER dynamically
    response = make_response(bp.send_static_file('bootstrap'))
    response.headers['Content-Type'] = 'text/x-python'
    return response

# Second Step: Bootstrap tells EOS to request config
@bp.route('/ztp/bootstrap/config')
def ztp_bootstrap_config():
    return jsonify({
        'xmpp': {},
        'logging': []
    })

# Third Step: EOS POSTs information
@bp.route('/ztp/nodes', methods=['POST'])
def ztp_nodes():
    '''
    {
    	"neighbors": {
    		"Management1": [{
    			"device": "b4fb.e488.56de",
    			"port": "0/6"
    		}]
    	},
    	"version": "4.21.8M",
    	"systemmac": "00:0c:29:a0:de:4d",
    	"model": "vEOS",
    	"serialnumber": ""
    }
    '''
    # Lookup device by serial number
    # If no device is found, lookup by MAC Address
    systemmac = request.json['systemmac'].replace(':', '')
    return redirect(url_for('eos.ztp_nodes_serial', serialnum=systemmac)), 409

# Fourth Step: We give EOS actions to do, actions are from ztpserver
# install_image - download and install specific firmware
# replace_config - download and install configuration
# copy_file - download and save file
@bp.route('/ztp/nodes/<serialnum>')
def ztp_nodes_serial(serialnum):
    # Look for Device

    actions = []

    # If not device, return unknown/no actions
    # return jsonify({
    #     'name': 'Unknown Device',
    #     'actions': []
    # }), 404

    # Upgrade Software Action if firmware set
    actions.append({
        'name': 'Upgrade Operating System',
        'action': 'install_image',
        'attributes': {
            'url': 'http://192.168.50.74:8000/firmware/vEOS-lab-4.22.2.1F.swi',
            'version': '4.22.2.1F'
        },
        'always_execute': True
    })
    # Get rendered configuration
    actions.append({
        'name': 'Install static startup-config file',
        'action': 'replace_config',
        'attributes': {
            'url': '/nodes/{}/startup-config'.format(serialnum)
        },
        'always_execute': True
    })
    # ZTP Finished Action
    actions.append({
        'name': 'Signal ZTP Completion',
        'action': 'copy_file',
        'attributes': {
            'src_url': '/{}/ztp_finished'.format(serialnum),
            'dst_url': '/mnt/flash',
            'mode': '0644',
            'overwrite': 'replace'
        },
        'always_execute': True
    })

    # JSON Out
    return jsonify({
        'name': 'Autogenerated definition',
        'actions': actions
    })

# Node retrieves install_image action file
@bp.route('/ztp/actions/install_image')
def ztp_actions_install_image():
    response = make_response(bp.send_static_file('actions/install_image'))
    response.headers['Content-Type'] = 'text/x-python'
    return response

# Node retrieves new firmware
# @bp.route('/ztp/files/images/vEOS-lab-4.22.2.1F.swi')
# def file_images():
#     response = make_response(bp.send_static_file('files/images/vEOS-lab-4.22.2.1F.swi'))
#     response.headers['Content-Type'] = 'application/vnd.aristanetworks.swi'
#     return response

# Node retrieves checksum for SWI
# @bp.route('/meta/files/images/<firmware>')
# def meta_firmware(firmware):
#     checksums = {
#         'md5': '3347e6e0ab6c33cd608e6067364485c6',
#         'sha512': '57def8fc84b1d3c808ab617ca4e8ccb3430dddba34b421f63203de78cbff05dbd15d15d39a4d10c0bf1c5cc8f032775b277d7d84dab7788f8c856350bdfe3d7c'
#     }
#     return checksums['md5']

# Node retrieves replace_config action file
@bp.route('/ztp/actions/replace_config')
def ztp_actions_replace_config():
    response = make_response(bp.send_static_file('actions/replace_config'))
    response.headers['Content-Type'] = 'text/x-python'
    return response

# Node retreives device-specific startup-config
@bp.route('/ztp/nodes/<serialnum>/startup-config')
def ztp_startup_config(serialnum):
    response = make_response(startup_config)
    response.headers['Content-Type'] = 'text/plain'
    return response

# Node retrieves checksum for startup-config
@bp.route('/ztp/meta/nodes/<serial>/startup-config')
def meta_serial_startup_config(serial):
    checksum = hashlib.sha1(startup_config.encode('utf-8')).hexdigest()
    size = len(startup_config)
    return jsonify({
        'sha1': checksum,
        'size': size
    })

# Node retrieves copy_file action file
@bp.route('/ztp/actions/copy_file')
def ztp_actions_copy_file():
    response = make_response(bp.send_static_file('actions/copy_file'))
    response.headers['Content-Type'] = 'text/x-python'
    return response

# Node retrieves the time it finished ZTP
@bp.route('/ztp/<serialnum>/ztp_finished')
def ztp_serial_ztp_finished(serialnum):
    now = datetime.now().strftime('%F %T')
    response = make_response('finished')
    response.headers['Content-Type'] = 'text/plain'
    return response

# Node retrieves checksum for ZTP finish time
@bp.route('/ztp/meta/<serialnum>/ztp_finished')
def meta_serial_ztp_finished(serialnum):
    checksum = hashlib.sha1('finished'.encode('utf-8')).hexdigest()
    size = len('finished')
    return jsonify({
        'sha1': checksum,
        'size': size
    })
